### ISSUE TITLE
General Configuration - Contradictory information

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#66]
1. Go to General Configuration Section
2. Then open Mail Configuration page

Results:
I'm on mail configuration page, but there is "system" selected on drop-down menu

https://image.prntscr.com/image/fzlcWk2ISlWdwOAMX7xCRg.png

**Comment by placidlyUnsalted** [comment]
@dawid-g Issue has been fixed.

**Comment by dawid-g** [comment]
Issue still persist on tablet and smartphone size:
https://image.prntscr.com/image/rE5S3L2mTjm3flIBYkRTTA.png

**Comment by placidlyUnsalted** [comment]
@dawid-g Please recheck admin panel - it has been recently updated.

**Comment by dawid-g** [comment]
verified as fixed ;)
