### ISSUE TITLE
[Tablet] Unable to enter data to input select2:tag

### ISSUE THREAD

**Issue by dawid-g** [antaresproject/antares-front-end#76]
Preconditions:
- tablet 9,7'

With regard to issue https://github.com/antaresproject/antares-front-end/issues/71, there is problem with entering data to input select2:tag on tablet.

Error: Unable to enter data to input select2:tag

**Comment by placidlyUnsalted** [comment]
@dawid-g Issue has been fixed.

**Comment by dawid-g** [comment]
Not fully fixed. Only two letters is allowed:


![notreally](https://user-images.githubusercontent.com/26220123/33065493-4d093a22-cea9-11e7-882d-e498e4393a4f.gif)

**Comment by dawid-g** [comment]
Not fully fixed. Only two letters is allowed:


![ns](https://user-images.githubusercontent.com/26220123/33065568-8512846e-cea9-11e7-8380-4b7721bf150c.gif)

**Comment by placidlyUnsalted** [comment]
@dawid-g Select should work fine on mobile devices after latest update.

**Comment by dawid-g** [comment]
It's ok now. Closed.
